apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-example
spec:
  type: LoadBalancer
  selector:
    app: kuard
    environment: prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080