apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-example-serviceaccount
  namespace: concepts
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  namespace: concepts
  name: security-example-clusterrole
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["endpoints", "pods", "secrets"]  
  verbs: ["get", "watch", "list"]
---
# The role binding to combine the secret-access service account and role
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: security-example-rolebinding
subjects:
- kind: ServiceAccount
  name: security-example-serviceaccount
  namespace: concepts  
roleRef:
  kind: ClusterRole
  name: security-example-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: security-example
  namespace: concepts  
spec:
  serviceAccountName: security-example-serviceaccount
  containers:
  - name: main
    image: tutum/curl
    command: ["sleep", "9999999"]
  - name: ambassador
    image: luksa/kubectl-proxy:1.6.2
